//! A generated RVA struct.

// DO NOT EDIT THIS FILE DIRECTLY.

/// A struct containing offsets (relative to the beginning of the executable) of
/// various addresses of structures and functions. They can be converted to a
/// usable address using the [Pe::rva_to_va] trait function of [Program].
///
/// These are populated from `mapper-profile.toml` in the root of this package
/// using `tools/binary-generator`.
pub struct RvaBundle {
    pub p2p_packet_dequeue: u32,
    pub p2p_send_packet: u32,
    pub sodium_kx_key_derive: u32,
}
