//! Generated RVA mappings for a single executable.

// DO NOT EDIT THIS FILE DIRECTLY.

use super::RvaBundle;

/// The RVAs for this executable.
///
/// These are populated from `mapper-profile.toml` in the root of this package
/// using `tools/binary-generator`.
pub const RVAS: RvaBundle = RvaBundle {
    p2p_packet_dequeue: 0x203f6a0,
    p2p_send_packet: 0x23f3ca0,
    sodium_kx_key_derive: 0x1e695d0,
};
